node{
    timestamps {
        dir("${WORKSPACE}"){
            stage ('Preparation'){
                try{
                    git 'https://github.com/ankurpatel18/testng8s3deploymentusingdocker.git'

                }catch(err){
                    sh 'echo "error occured in build"'
                    throw err;
                }
            }

            stage ('Build docker container'){
                sh label: 'docker container', script: '''ls
                    docker info
                    docker build -t ankurpatel18/testNg8DeploymentUsingDocker:${BUILD_NUMBER} .
                    docker tag ankurpatel18/testNg8DeploymentUsingDocker:${BUILD_NUMBER} ankurpatel18/testNg8DeploymentUsingDocker:latest
                    docker images
                    '''
            }
        }
    }
}
