node{
    timestamps {
        dir("${WORKSPACE}"){
            stage ('Preparation'){
                try{
                    git 'https://gitlab.com/theoankur/testng8s3deploymentartifacts.git'
                    // checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'PerBuildTag']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://gitlab.com/theoankur/testng8s3deploymentartifacts.git']]])
                }catch(err){
                    sh 'echo "error occured in build"'
                    throw err;
                }
            }
            
            nodejs('NodeJS') {
                stage ('Install dependencies') {
                    sh 'npm install'
                }

                stage ('Build'){
                    sh 'npm run build'
                }
            }
            dir('dist/'){
                 stage ('Generate Artifact') {
                    zip archive: false, dir: 'testNg8Deployment', glob: '', zipFile: "${JOB_NAME}_${BUILD_NUMBER}.zip"
                    archiveArtifacts artifacts: "${JOB_NAME}_${BUILD_NUMBER}.zip", fingerprint: true
                }
                stage('Approval to Deploy'){
                    script {
                        timeout(time: 2, unit: 'MINUTES') {
                            input(id: "Deployment Approval", message: "Are you approving deploy of ${JOB_NAME}_${BUILD_NUMBER}?", ok: 'Deployment')
                        }
                    }
                }
                stage('Deployment'){
                    withAWS(credentials: 'awsS3acesssForJenkins', region: 'ap-south-1') {
                        s3Upload acl: 'Private', bucket: 'jenkins-deployment-artifacts-2019', file: "${JOB_NAME}_${BUILD_NUMBER}.zip", path: 'testNg8Deployment/'
                        // s3CopyArtifact buildSelector: lastSuccessful(stable: true), filter: 'testNg8Deployment.zip', flatten: false, optional: false, projectName: 'testNg8Deployment', target: 'testNg8Deployment/'
                    }
                }
            }
        }
    }
}